services:
  database:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mkp_test_db
    ports:
      - 5433:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      - DB_DRIVER=postgres
      - DB_URL=postgres://postgres:admin@database:5432/mkp_test_db?sslmode=disable
      - DB_USERNAME=postgres
      - DB_PASSWORD=admin
      - DB_DATABASE=mkp_test_db
      - DB_HOST=database
      - DB_PORT=5432
      - PORT=3000
      - KEY=ditoadriel1234567890
      - EXPIRED=2
    ports:
      - 3000:3000